### PR TITLE
Composer package name case insensitive

### PR DESCRIPTION
**Pull request by Roquie**
Hello!
Please, follow the link and see note block.
https://getcomposer.org/doc/02-libraries.md#every-project-is-a-package

### CODE REVIEW

**Comment by lavoiesl** [comment]
In that case, I think you should be using [`strcasecmp`](http://php.net/manual/en/function.strcasecmp.php)

**Comment by Roquie** [comment]
yeah, so is it really better :)

**Comment by lemoinem** [comment]
Much better, could you squash your commits and we'll merge them.

Thanks for the fix!

**Comment by Roquie** [comment]
Done.

**Comment by lemoinem** [comment]
Thanks! :+1:

**Pull request merged**
