### PR TITLE
Handling base64 encoded composer.json file

### PR DESCRIPTION
**Pull request by simare**
Hello, 

I switched to Repository::getFile() because Repository::blob() returns the base64 string with a prefix which I did not want to take care of.
This should solve issue #24
Best,
Ramon

### CODE REVIEW

**Comment by lemoinem** [comment]
Hi!

First of all, thanks for the PR.

However, do you think it would be possible to switch the behavior based on the actual GitLab version that is used?
I wouldn't want people with older versions of GitLab to have their installation stop working (Granted they should keep their installation of GitLab up-to-date, but may not do so for other reasons...)

**Comment by simare** [comment]
Hi,yes that seems reasonable. Do you know how to get the version via the API and also with which version  this change was introduced? Am 24.01.2017 16:26 schrieb Mathieu Lemoine <notifications@github.com>:Hi!
First of all, thanks for the PR.
However, do you think it would be possible to switch the behavior based on the actual GitLab version that is used?
I wouldn't want people with older versions of GitLab to have their installation stop working (Granted they should keep their installation of GitLab up-to-date, but may not do so for other reasons...)

**Comment by lemoinem** [comment]
Well, as far as I can see, neither the API doc nor the code in our library seem to change from 6 (in which it was working) to 8/master...
Tell you what, we will just merge this as-is and if people complain, we will direct them here and eventually work out the correct version test.

Thanks for the contribution!

**Comment by simare** [comment]
The PR resolves this issue. Thank you.

**Pull request merged**
